#25 サインアップページUIの作成
if-mentor/next_fire_todo_5 pull request #63
Opened 2022-05-11 06:14 UTC by mogy-h

## IssueのURL
#25 

## 対応内容・対応背景・妥協点
サインアップUIの作成

## やったこと
#24 のログインページのレイアウトに合わせて作成
パスワードの可視化切り替えの実装

## やってないこと・できていないこと
 半年ぶりくらいに学習再開したのもあり、typescript, material-uiの書き方を忘れてしまっている部分が多く、足りない記述や効率の悪い書き方になっているかもしれません。
改善点があればご指摘いただけると幸いです。

## UI
<img width="1440" alt="スクリーンショット 2022-05-11 15 08 20" src="https://user-images.githubusercontent.com/68378904/167780677-473cbcd0-31a8-438d-9af9-af1220391c95.png">
<img width="1440" alt="スクリーンショット 2022-05-11 15 08 25" src="https://user-images.githubusercontent.com/68378904/167780603-f3255f63-7241-4eda-97a2-82e26cd1e082.png">

## テスト
# コンソールに文字列の出力
# パスワード可視不可視の確認

## レビュー観点
あくまで目安です。

- 想定通りに動作するか？
- より良いJS/JSX/TS/TSX/CSS/Reactの書き方はないか？
- より良い設計方法はないか？
- 他の部分と書き方・命名・ディレクトリ構成等が異なっていないか？
- 関数、コンポーネントの粒度は適切か？
- etc...

2022-05-12 05:13 UTC, Yukitkym requested changes
機能もデザインも基本的には大丈夫だと思います！
Headerの部分がまだ作成されていない問題と、package周りでコンフリクトが起きている問題が発生しているので、最新版をpullして再度pushをお願いいたします。
あとはサインアップページなので、パスワードの確認用の欄があっても良いかなと思いました。

2022-05-12 05:13 UTC, Yukitkym commented on pages/signUp.tsx
> +  Checkbox,
import周りで使っていないものは削除したほうが良いと思います。

2022-05-12 05:13 UTC, Yukitkym commented on pages/signUp.tsx
> +import { Header } from "../components/Header";
Headerがない状態で読み込もうとしているため、エラーが起きているようです。
最新の状態のorigin mainをpullしてくればエラーが治ると思います。

2022-05-12 05:13 UTC, Yukitkym commented on pages/signUp.tsx
> +          <Avatar sx={{ m: 1, bgcolor: "secondary.main" }}>{/* <LockOutlinedIcon /> */}</Avatar>
コメントアウトした部分が一部残ってしまっているようです。

2022-05-12 05:15 UTC, Yukitkym commented
IssueのURLとAssigneesはこちらを参考に直した方が良いかなと思いました。
https://github.com/if-mentor/next_fire_todo_5/pull/52#pullrequestreview-965332788

2022-05-13 13:25 UTC, Yukitkym requested changes
yarn add @mui/icons-materialをお願いいたします。

2022-05-13 13:25 UTC, Yukitkym commented on package.json
>      "@mui/material": "^5.6.4",
@mui/icons-materialがyarn addされてなく、signUpページでエラーが起きているようです。

2022-05-14 07:47 UTC, Junkichi89 commented on components/Header.tsx
> +      <Box
```suggestion
      <Flex
```

2022-05-14 07:48 UTC, Junkichi89 commented on components/Header.tsx
> +          background: "#68D391",
```suggestion
        sx={{
          display: "block",
          alignItems: "center",
          width: "88%",
          height: "80px",
          background: "#68D391",
```

2022-05-14 07:49 UTC, Junkichi89 commented on components/Header.tsx
> +          background: "#68D391",
```suggestion
        sx={{
          display: "flex",
          alignItems: "center",
          width: "100%",
          height: "80px",
          background: "#68D391",
```

2022-05-14 08:48 UTC, Yukitkym approved these changes

2022-05-14 08:51 UTC, merged