#18 todoの詳細画面作成
if-mentor/next_fire_todo_5 pull request #65
Opened 2022-05-13 13:11 UTC by naokitime

## IssueのURL

https://github.com/if-mentor/next_fire_todo_5/issues/18

## 対応内容・対応背景・妥協点

対応内容；Todoアプリの詳細画面作成
妥協点：Boxに対してクラス名やcomponent名を付けてない

## やったこと

Todoアプリの詳細画面作成、ひとまず形にした

## やってないこと・できていないこと

ボタンのイベント追加
component名を付けてない
文字数が多く入った時の対応
エラーの解消：3つのエラーが発生している。まだ未解明

## UI before / after
UIや振る舞いが変わる場合はbefore / afterのスクショや動画を共有する
<img width="1425" alt="スクリーンショット 2022-05-13 22 07 38" src="https://user-images.githubusercontent.com/86907715/168290178-0f0e30e0-399a-4897-98ee-c64f56579bac.png">

## テスト

detailの部分のみ長文が入った場合に、文字が折り返す様確認した

## レビュー観点
あくまで目安です。

- 想定通りに動作するか？
- より良いJS/JSX/TS/TSX/CSS/Reactの書き方はないか？
- より良い設計方法はないか？
- 他の部分と書き方・命名・ディレクトリ構成等が異なっていないか？
- 関数、コンポーネントの粒度は適切か？
- etc...

## 補足

全然綺麗なコードでないと思いますが、「もっとこう書くと良い」というアドバイスがあればお願いします。

2022-05-13 14:10 UTC, Yukitkym requested changes
エラーの部分と、画面サイズを小さくした際への挙動の対策をレビューいたしました。
お手数ですが、修正の方よろしくお願いいたします。

2022-05-13 14:10 UTC, Yukitkym commented on pages/detail.tsx
> +        <Box sx={{ textAlign: "right", mb: -5}} >
こちらの16〜23行目のBoxを26〜35行目のBoxの中(27〜34行目のTypographyの直下)に入れてあげると、画面サイズが小さくなったときにも文字に被らないかと思います。
26〜35行目のBoxにはdisplay: "flex"を、16〜23行目のBoxにはmb: -5を削除しmarginLeft: "auto"を当ててあげればある程度良い感じになるかと思います。

2022-05-13 14:10 UTC, Yukitkym commented on pages/detail.tsx
> +        <Box>
こちらの36行目のBoxにsx={{ overflowX: "auto"}}を追記すれば、画面サイズが小さくなってもはみ出なくなりそうです。

2022-05-14 01:12 UTC, naokitime commented on pages/detail.tsx
> +                    <TableCell sx={{ fontSize: "24px", fontWeight: "bold", background: "#68D391" }}>
TableRowを挿入するとエラーが解消しました。ありがとうございます。

2022-05-14 05:32 UTC, Yukitkym approved these changes
LGTM!

2022-05-14 06:11 UTC, merged